### ISSUE TITLE
I am the Chinese translator of your book

### ISSUE THREAD

**Issue by weiminye** [abdullahkarasan/mlfrm#8]
Hi Abdullah,

I am the Chinese translator of your book. 
This is my LinkedIn profile:
https://www.linkedin.cn/injobs/in/weimin-ye-9203806

In order to get the best quality of the translation, could you add me via Linkedin and we can communicate more?

**Comment by abdullahkarasan** [comment]
Hello Weimin,

Nice to meet you. I tried to find your profile but I do not know why I
could not locate it. You can add me from here:
www.linkedin.com/in/abdullahkarasan
Best
Abdullah

**Comment by weiminye** [comment]
Hi Abdullah,

I could not locate you too, that is interesting.

Anyway, you can send me email: 

billyinusa at outlook.com

Just replace the at to @ 
Hope we have a good cooperation
